apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: web
  template:
    metadata:
      labels:
        app: backend
        tier: web
    spec:
      serviceAccountName: backend
      containers:
      - image: gcr.io/cloudsql-docker/gce-proxy:1.17
        imagePullPolicy: Always
        name: cloud-sql-proxy
        command:
          - "/cloud_sql_proxy"
        args:
          - "-instances=above-the-clouds-app:us-central1:$(DB_ADDRESS)=tcp:5432"
        env:
        - name: DB_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backend
              key: db_address
        securityContext:
          runAsNonRoot: true
      - image: gcr.io/above-the-clouds-app/backend:1.0.1
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          name: web-app-port
        - containerPort: 8000
          name: socket-port
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: backend
              key: env
        - name: WEB_URL
          valueFrom:
            configMapKeyRef:
              name: backend
              key: web_url
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            configMapKeyRef:
              name: backend
              key: twilio_account_sid
        - name: TWILIO_API_KEY
          valueFrom:
            configMapKeyRef:
              name: backend
              key: twilio_api_key
        - name: TWILIO_SERVICE_SID
          valueFrom:
            configMapKeyRef:
              name: backend
              key: twilio_service_sid
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: postgres-password
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: sendgrid_api_key
        - name: TWILIO_API_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: twilio_api_secret
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: twilio_auth_token
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
