apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: web
  template:
    metadata:
      labels:
        app: backend
        tier: web
    spec:
      serviceAccountName: cloud-sql-proxy-sa
      containers:
      - image: gcr.io/cloudsql-docker/gce-proxy:1.17
        imagePullPolicy: Always
        name: cloud-sql-proxy
        command:
          - "/cloud_sql_proxy"
          - "-instances=above-the-clouds-app:us-central1:above-the-clouds-dbs=tcp:5432"
        securityContext:
          runAsNonRoot: true
      - image: gcr.io/above-the-clouds-app/backend:1.0.0
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "prod"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
