apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
data:
  db_address: above-the-clouds-dbs
  env: prod
  web_url: https://www.abovethecloudsapp.com
  twilio_account_sid: AC7c31539494f6bb6b303c63d0368b0818
  twilio_api_key: SK5b001f6fc9498e04c60d74a3c3cea856
  twilio_service_sid: IS939e3e0527de55bd022581ba9670659a
